secret_key_base: 8+YXbM7CYGIsrHa/lK132LWOx/RHL2brmUHTdIUnfo1xQkLL2zeA8c0I67GhQ2l86oJqk2DKEROdWhriR6JeOyJMPEhZmX8o5/nU7zGEAytSlz+ekkio4G5/8KchaNOM8zkhKcjJgsMwXF7XARwX9JBAQ+v5Bsbc00NHme82RNfahftmVJx/ruYTDAwIiIXuhpmiE4oDRmtqIUbPlS2RXz3UlSmK4bhXxyVNMRvHM0BmXPZ3/aAkywMl6vIy4EXsIShx/L+21CT0OlruGXNPLhnMZdM/MJUvzjWwiiXZm/sY4cD7MSI2heLs33ErXXqQRptPuJgY/RAHzPhoAEQXXxwiHKybJIXdfOldxgNtta0YJY2n0eQcb0jshb8EeOCB8bgZXG8rJyYINcII4d6MSTlNWja1--ZbrmbDq1aB7xByFq--HDOHF9f5+TdXcVEVA7+KKA==

active_record_encryption:
  primary_key: J5X4ScP20sgvQ8hzO3MYl2BzEPbKUkvG
  deterministic_key: 8bdi7NZDzLbhsTzhP49vQjhR0NdTtPYT
  key_derivation_salt: FO5siLhvwljhvHN7hgKcRhepW00CYuvD